// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xjmqdtphofzcckqnniei.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhqbXFkdHBob2Z6Y2NrcW5uaWVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMDAwMDEsImV4cCI6MjA2Mjg3NjAwMX0.tisF6WZien4zpz3RYw5sZsb556SFsVNQOHBRrIUna6g";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);